### ISSUE TITLE
As a website user, I want to be able to sort the answers posted for a specific asked question so that the more relevant answers appear on the top and become more accessible to all users

### ISSUE THREAD

**Issue by Arsollo** [Arsollo/Soen-341-Project#13]

**Comment by mathildetq** [comment]
Features for answers:

- [ ] Sort answers based on date
- [ ] Sort answers based on votes
- [ ] Top the best accepted answer

**Comment by mathildetq** [comment]
This issue needs to be closed for tomorrow, can someone confirm that they were done? and check the task list! @krishnnas @Arsollo @SheriefS

**Comment by Arsollo** [comment]
Still working on it

**Comment by SheriefS** [comment]
By default it is sorting by date. We have not implemented any sorting feature at this time, and this should be considered an additional feature as it is not listed as one of the three core features.

**Comment by SheriefS** [comment]
Changed wording in user story to be sort rather than rank.

**Comment by mathildetq** [comment]
As this is not a core feature, but an extra feature, which is optional, it should be dealt with if we have time.
