### ISSUE TITLE
As a website user, I want to be able to accept or deny an answer for my questions so that I make sure only legitimate answers are provided

### ISSUE THREAD

**Issue by Arsollo** [Arsollo/Soen-341-Project#19]

**Comment by SheriefS** [comment]
I don't think this is a feature we want to implement. With a voting system in place, we should not be giving front end users the ability to add or remove information. We may want to consider some kind of admin permissions for the site with these capabilities. I we re in agreement, please close this and tag as in invalid..

**Comment by mathildetq** [comment]
I agree with, I will be tagging as invalind and closing this issue.
