### ISSUE TITLE
See if website.html is useful 

### ISSUE THREAD

**Issue by mathildetq** [Arsollo/Soen-341-Project#35]
The website.html (Layout) seems not linked up to any html file. The layout.html and home.html are used for the pages layout. Check if we can delete it.

**Comment by SheriefS** [comment]
It can be safetly removed, base template for the rest is in home.html

**Comment by mathildetq** [comment]
Great I will do a pull request to delete it

**Comment by Arsollo** [comment]
yep, we can simply remove it
