### ISSUE TITLE
Need Verification of System Architecture

### ISSUE THREAD

**Issue by mathildetq** [Arsollo/Soen-341-Project#65]
Could you please verify this architecture, I followed MVC and https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/twitter/README.md .
I will add it to the WikiPage afterwards

![System Architecture](https://user-images.githubusercontent.com/91547964/144783801-89f81965-1649-4a34-80ac-90113cb93a16.png)

**Comment by SheriefS** [comment]
This is correct

**Comment by Arsollo** [comment]
Ready to upload!

**Comment by mathildetq** [comment]
Okay closing and
