### ISSUE TITLE
Verification Example Login Architecture

### ISSUE THREAD

**Issue by mathildetq** [Arsollo/Soen-341-Project#66]
Please verify the login Architecture that follows Model View Controller. 
Same as before I will download to the WikiPage once verified. 
![LoginMVC](https://user-images.githubusercontent.com/91547964/144784084-05219bda-2a4b-4f2f-96c7-489464a3d6d4.png)

**Comment by SheriefS** [comment]
This is correct

**Comment by Arsollo** [comment]
Ready for upload!
