### ISSUE TITLE
Verification UML Diagram

### ISSUE THREAD

**Issue by mathildetq** [Arsollo/Soen-341-Project#67]
PLease verify the UML Diagram. Let me know if I am missing classes or the functions are at the wrong place.
I will upload to the WikiPage afterwards. 
![UML_Diagram](https://user-images.githubusercontent.com/91547964/144784296-64dd1060-81d8-48ba-82e2-7993d4e9c32e.png)

**Comment by SheriefS** [comment]
Just to confirm, this indicates multiple answers to be associated with a question?

**Comment by mathildetq** [comment]
@SheriefS Yes so * means 0 to "infinity". So for one question you can have many answers.

**Comment by SheriefS** [comment]
Then this also looks good to me

**Comment by Arsollo** [comment]
I think the class variables need some reviewing --> some instance variables are missing and some instance variables have wrong data types
